### ISSUE TITLE
False positive warning on action insertorupdate

### ISSUE THREAD

**Issue by koos-luijk** [MichielJanssen1991/PetrelLanguageServer#13]
Which is logic since it is not defined by the action. 

![image](https://user-images.githubusercontent.com/86042052/147750925-53588f57-db3e-4c61-8b30-de106afaca1c.png)

Probably check if there is an argument defined as a "*". If so, this check could be skipped. 
Additional we might check the related type, but that's for another milestone

**Comment by MichielJanssen1991** [comment]
Issue has been resolved!
